apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-explorer-controller-manager
  labels:
    app: pvc-explorer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pvc-explorer
  template:
    metadata:
      labels:
        app: pvc-explorer
    spec:
      serviceAccountName: {{ include "pvc-explorer.serviceAccountName" . }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: health
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
