apiVersion: pvcexplorer.io/v1alpha1
kind: PVCExplorerScope
metadata:
  name: demo-by-label
spec:
  namespaces:
    labelSelector:
      matchLabels:
        pvc-explorer: enabled
  discovery:
    mode: Auto
    excludePVCs:
      - "tmp-*"
  deletionPolicy: Cleanup
  defaults:
    mode: ScaledToZero
    image: ghcr.io/pvc-explorer-operator/pvc-explorer-agent:dev
    forceRW: true
    scaling:
      idleTimeout: "5m"
      startupTimeout: "60s"
    mountStrategy:
      allowNodeAffinity: true
      fallbackOnConflict: Pending
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
