//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerInfo) DeepCopyInto(out *ConsumerInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerInfo.
func (in *ConsumerInfo) DeepCopy() *ConsumerInfo {
	if in == nil {
		return nil
	}
	out := new(ConsumerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountStatus) DeepCopyInto(out *MountStatus) {
	*out = *in
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = make([]ConsumerInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountStatus.
func (in *MountStatus) DeepCopy() *MountStatus {
	if in == nil {
		return nil
	}
	out := new(MountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountStrategySpec) DeepCopyInto(out *MountStrategySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountStrategySpec.
func (in *MountStrategySpec) DeepCopy() *MountStrategySpec {
	if in == nil {
		return nil
	}
	out := new(MountStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorer) DeepCopyInto(out *PVCExplorer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorer.
func (in *PVCExplorer) DeepCopy() *PVCExplorer {
	if in == nil {
		return nil
	}
	out := new(PVCExplorer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PVCExplorer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerList) DeepCopyInto(out *PVCExplorerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PVCExplorer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerList.
func (in *PVCExplorerList) DeepCopy() *PVCExplorerList {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PVCExplorerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerScope) DeepCopyInto(out *PVCExplorerScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerScope.
func (in *PVCExplorerScope) DeepCopy() *PVCExplorerScope {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PVCExplorerScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerScopeList) DeepCopyInto(out *PVCExplorerScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PVCExplorerScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerScopeList.
func (in *PVCExplorerScopeList) DeepCopy() *PVCExplorerScopeList {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PVCExplorerScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerScopeSpec) DeepCopyInto(out *PVCExplorerScopeSpec) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
	in.Discovery.DeepCopyInto(&out.Discovery)
	in.Defaults.DeepCopyInto(&out.Defaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerScopeSpec.
func (in *PVCExplorerScopeSpec) DeepCopy() *PVCExplorerScopeSpec {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerScopeStatus) DeepCopyInto(out *PVCExplorerScopeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerScopeStatus.
func (in *PVCExplorerScopeStatus) DeepCopy() *PVCExplorerScopeStatus {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerScopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerSpec) DeepCopyInto(out *PVCExplorerSpec) {
	*out = *in
	if in.ExplorerLabels != nil {
		in, out := &in.ExplorerLabels, &out.ExplorerLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Scaling = in.Scaling
	out.MountStrategy = in.MountStrategy
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerSpec.
func (in *PVCExplorerSpec) DeepCopy() *PVCExplorerSpec {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCExplorerStatus) DeepCopyInto(out *PVCExplorerStatus) {
	*out = *in
	in.Mount.DeepCopyInto(&out.Mount)
	out.Agent = in.Agent
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCExplorerStatus.
func (in *PVCExplorerStatus) DeepCopy() *PVCExplorerStatus {
	if in == nil {
		return nil
	}
	out := new(PVCExplorerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSpec.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeDefaultsSpec) DeepCopyInto(out *ScopeDefaultsSpec) {
	*out = *in
	out.Scaling = in.Scaling
	out.MountStrategy = in.MountStrategy
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeDefaultsSpec.
func (in *ScopeDefaultsSpec) DeepCopy() *ScopeDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeDiscoverySpec) DeepCopyInto(out *ScopeDiscoverySpec) {
	*out = *in
	if in.PVCNames != nil {
		in, out := &in.PVCNames, &out.PVCNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludePVCs != nil {
		in, out := &in.ExcludePVCs, &out.ExcludePVCs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeDiscoverySpec.
func (in *ScopeDiscoverySpec) DeepCopy() *ScopeDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(ScopeDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeMountStrategySpec) DeepCopyInto(out *ScopeMountStrategySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeMountStrategySpec.
func (in *ScopeMountStrategySpec) DeepCopy() *ScopeMountStrategySpec {
	if in == nil {
		return nil
	}
	out := new(ScopeMountStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeNamespacesSpec) DeepCopyInto(out *ScopeNamespacesSpec) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeNamespacesSpec.
func (in *ScopeNamespacesSpec) DeepCopy() *ScopeNamespacesSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeNamespacesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeScalingSpec) DeepCopyInto(out *ScopeScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeScalingSpec.
func (in *ScopeScalingSpec) DeepCopy() *ScopeScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeScalingSpec)
	in.DeepCopyInto(out)
	return out
}
